version: '3'
services:
  nemo-1:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    ports:
      # open default nemo rpc port
      - "26657:26657"
      # open rest port
      - "1317:1317"
      # open grpc port
      - "9090:9090"
      # open grpc-web port
      - "9091:9091"
      # open EVM JSON-RPC port
      - "8545:8545"
      # open Eth websocket port
      - "8546:8546"
    volumes:
      - "./nemo-1:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-2:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-2:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-3:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-3:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-4:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-4:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-5:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-5:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-6:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-6:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-7:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-7:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-8:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-8:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-9:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-9:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-10:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-10:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-11:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-11:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-12:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-12:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
  nemo-13:
    image: "nemo/fury:${FURY_IMAGE_TAG:-master}"
    volumes:
      - "./nemo-13:/root/.nemo"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants"
