version: '3'

services:
    ibcnode:
        image: "nemo/nemo:v0.21.0"
        # use the default ports, but shift them when exposing to host so they dont conflict.
        ports:
            # open rpc port
            - "26658:26657"
            # open rest port
            - "1318:1317"
            # open grpc port
            - "9092:9090"
            # open grpc-web port
            - "9093:9091"
            # evm json-rpc
            - "8547:8545"
            # evm websocket json-rpc
            - "8548:8546"
        volumes:
            - "./ibcchain/initstate/.nemo/config:/root/.nemo/config"
            - "./ibcchain/initstate/.nemo/keyring-test/:/root/.nemo/keyring-test"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command:
            [
                "sh",
                "-c",
                "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657"
            ]
