version: "3"

services:
  nemonode:
    image: "nemo/nemo:${NEMO_TAG:-v0.14.1}"
    ports:
      # open default nemo rpc port
      - "26657:26657"
    volumes:
      - "./nemo/initstate/.nmd/config:/root/.nmd/config"
      - "./nemo/initstate/.kvcli/:/root/.kvcli/"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      [
        "sh",
        "-c",
        "/root/.nmd/config/init-data-directory.sh && nmd start --pruning=nothing --rpc.laddr=tcp://0.0.0.0:26657"
      ]
  nemorest:
    image: "nemo/nemo:${NEMO_TAG:-v0.14.0}"
    ports:
      # open default rest port
      - "1317:1317"
    command:
      [
        "kvcli",
        "rest-server",
        "--node=tcp://nemonode:26657",
        "--trust-node",
        "--laddr=tcp://0.0.0.0:1317",
        "--unsafe-cors"
      ]
