version: '3'
services:
    nemonode:
        image: "nemo/nemo:${NEMO_TAG:-v0.16}"
        ports:
            # open default nemo rpc port
            - "26657:26657"
            # open rest port
            - "1317:1317"
            # open grpc port
            - "9090:9090"
            # open grpc-web port
            - "9091:9091"
        volumes:
            - "./nemo/initstate/.nemo/config:/root/.nemo/config"
            - "./nemo/initstate/.nemo/keyring-test/:/root/.nemo/keyring-test"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command: ["sh", "-c", "/root/.nemo/config/init-data-directory.sh && nemo start --rpc.laddr=tcp://0.0.0.0:26657"]
